import React, { createContext, useContext, useState, useEffect } from "react";
import { supabase } from "../utils/supabase";

type Language = "en" | "hi" | "bn" | "ta" | "te" | "mr" | "gu" | "kn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  // ... (translations remain the same, truncated for brevity in this view but will be preserved in file)
  hi: {
    dashboard: "डैशबोर्ड",
    analyze: "विश्लेषण करें",
    evidence: "सबूत",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",
    welcome: "वापसी पर स्वागत है",
    recent_analysis: "हालिया विश्लेषण",
    new_analysis: "नया विश्लेषण",
    funding_fit: "फंडिंग फिट",
    startup_description: "स्टार्टअप विवरण",
    sector: "सेक्टर",
    funding_stage: "फंडिंग स्टेज",
    geography: "भूगोल",
    language_settings: "भाषा सेटिंग्स",
    interface_lang: "इंटरफेस भाषा",
    interface_lang_desc: "इस भाषा का उपयोग फंडिंगसेंस इंटरफेस में किया जाएगा",
    report_lang: "रिपोर्ट भाषा",
    report_lang_desc: "फंडिंग विश्लेषण रिपोर्ट डिफ़ॉल्ट रूप से इस भाषा में उत्पन्न की जाएगी।",
    save_prefs: "वरीयताएँ सहेजें",
    about_multilingual: "बहुभाषी समर्थन के बारे में",
    about_multilingual_desc: "फंडिंगसेंस 8 प्रमुख भारतीय भाषाओं का समर्थन करता है, जिससे संस्थापकों और निवेशकों को उनकी पसंदीदा भाषा में फंडिंग इंटेलिजेंस तक पहुंचने में मदद मिलती है।",
    view_all: "सभी देखें",
    no_analyses: "कोई विश्लेषण नहीं मिला. इसे देखने के लिए अपना पहला विश्लेषण चलाएँ!",
    loading_analyses: "हालिया विश्लेषण लोड हो रहा है...",
    loading_evidence: "सबूत लोड हो रहा है...",
    just_now: "अभी अभी",
    fit_score: "फिट स्कोर",
    confidence: "आत्मविश्वास",
    analyses_run: "विश्लेषण चलाए गए",
    investors_matched: "निवेशक मिलान किए गए",
    evidence_points: "सबूत अंक",
    avg_fit_score: "औसत फिट स्कोर",
    toggle_theme: "थीम बदलें",
    search_sources: "स्रोत खोजें...",
    all_types: "सभी प्रकार",
    news: "समाचार",
    policy: "नीति",
    dataset: "डेटासेट",
    used_for: "के लिए उपयोग किया जाता है",
    report_title: "फंडिंग निर्णय रिपोर्ट",
    report_desc: "आपके स्टार्टअप के लिए साक्ष्य-समर्थित विश्लेषण",
    why_fits: "यह क्यों फिट बैठता है",
    considerations: "विचार",
    recommended_investors: "अनुशंसित निवेशक",
    sources_used: "इस विश्लेषण के लिए उपयोग किए गए स्रोत",
    run_new: "नया विश्लेषण चलाएँ",
    view_evidence: "सभी सबूत देखें",
    total_sources: "कुल संग्रहीत स्रोत",
    how_it_works: "यह कैसे काम करता है?",
    how_it_works_desc: "हमारा AI आपके स्टार्टअप का हजारों सफल फंडिंग राउंड, निवेशक पोर्टफोलियो और नीति दस्तावेजों के मुकाबले विश्लेषण करके साक्ष्य-समर्थित सिफारिशें प्रदान करता है।",
    analyzing: "विश्लेषण संसाधित किया जा रहा है...",
    missing_info: "जानकारी गायब है",
    no_risks_found: "प्रदान किए गए डेटा के आधार पर कोई महत्वपूर्ण जोखिम नहीं पाया गया।",
    analysis_completed: "विश्लेषण पूरा हुआ",
    match: "मिलान",
    key_reasons: "मुख्य कारण",
    q_and_a: "प्रश्न और उत्तर",
    chat_with_ai: "एआई के साथ चैट करें",
    select_context: "संदर्भ के लिए अपना स्टार्टअप चुनें",
    type_message: "अपना संदेश टाइप करें...",
    no_startups_yet: "अभी तक कोई स्टार्टअप नहीं",
    keep_dreaming: "सपने देखते रहें, बड़ा सोचें!",
    analyzing_fit: "फिट कारकों का विश्लेषण किया जा रहा है...",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    interface_desc: "अपने स्थानीय अनुभव को अनुकूलित करें",
    report_lang_selection_desc: "अपनी गहन विश्लेषण रिपोर्टों के लिए डिफ़ॉल्ट पीढ़ी भाषा सेट करें।",
    did_you_know: "क्या आप जानते हैं?",
    did_you_know_desc: "अपनी UI भाषा बदलने से सभी नेविगेशन, त्रुटि संदेश और सिस्टम अंतर्दृष्टि तुरंत अपडेट हो जाती हैं।",
    localization_tech: "स्थानीयकरण तकनीक",
    localization_tech_desc: "हमारे आरएजी मॉडल स्वचालित रूप से चयनित सांस्कृतिक संदर्भ और भाषाई बारीकियों के लिए साक्ष्य निष्कर्षण को अनुकूलित करते हैं।"
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    analyze: "বিশ্লেষণ করুন",
    evidence: "প্রমাণ",
    settings: "সেটিংস",
    logout: "লগ আউট",
    welcome: "ফিরে স্বাগতম",
    recent_analysis: "সাম্প্রতিক বিশ্লেষণ",
    new_analysis: "নতুন বিশ্লেষণ",
    funding_fit: "তহবিল ফিট",
    startup_description: "স্টার্টআপ বিবরণ",
    sector: "ক্ষেত্র",
    funding_stage: "তহবিল পর্যায়",
    geography: "ভৌগোলিক অবস্থান",
    language_settings: "ভাষা সেটিংস",
    interface_lang: "ইন্টারফেস ভাষা",
    interface_lang_desc: "এই ভাষাটি ফান্ডিংসেন্স ইন্টারফেস জুড়ে ব্যবহৃত হবে",
    report_lang: "রিপোর্ট ভাষা",
    report_lang_desc: "তহবিল বিশ্লেষণ প্রতিবেদনগুলি ডিফল্টরূপে এই ভাষায় তৈরি করা হবে।",
    save_prefs: "পছন্দ সংরক্ষণ করুন",
    about_multilingual: "বহুভাষিক সমর্থন সম্পর্কে",
    about_multilingual_desc: "ফান্ডিংসেন্স 8 টি প্রধান ভারতীয় ভাষাকে সমর্থন করে, যা প্রতিষ্ঠাতা এবং বিনিয়োগকারীদের তাদের পছন্দের ভাষায় তহবিল বুদ্ধিমত্তা অ্যাক্সেস করতে সক্ষম করে।",
    view_all: "সব দেখান",
    no_analyses: "কোন বিশ্লেষণ পাওয়া যায়নি। এটি দেখতে আপনার প্রথম বিশ্লেষণ চালান!",
    loading_analyses: "সাম্প্রতিক বিশ্লেষণ লোড হচ্ছে...",
    loading_evidence: "প্রমাণ লোড হচ্ছে...",
    just_now: "এইমাত্র",
    fit_score: "ফিট স্কোর",
    confidence: "আত্মবিশ্বাস",
    analyses_run: "বিশ্লেষণ চালানো হয়েছে",
    investors_matched: "বিনিয়োগকারীদের সাথে মিলেছে",
    evidence_points: "প্রমাণ পয়েন্ট",
    avg_fit_score: "গড় ফিট স্কোর",
    toggle_theme: "থিম টগল করুন",
    search_sources: "উত্স সন্ধান করুন...",
    all_types: "সমস্ত প্রকার",
    news: "খবর",
    policy: "নীতি",
    dataset: "ডেটা সেট",
    used_for: "জন্য ব্যবহৃত",
    report_title: "তহবিল সিদ্ধান্ত প্রতিবেদন",
    report_desc: "আপনার স্টার্টআপের জন্য প্রমাণ-সমর্থিত বিশ্লেষণ",
    why_fits: "কেন এটি ফিট করে",
    considerations: "বিবেচনা",
    recommended_investors: "প্রস্তাবিত বিনিয়োগকারী",
    sources_used: "এই বিশ্লেষণের জন্য ব্যবহৃত উত্স",
    run_new: "নতুন বিশ্লেষণ চালান",
    view_evidence: "সমস্ত প্রমাণ দেখুন",
    total_sources: "মোট উত্স আর্কাইভ করা হয়েছে",
    how_it_works: "এটি কিভাবে কাজ করে?",
    how_it_works_desc: "আমাদের এআই আপনার স্টার্টআপকে হাজার হাজার সফল তহবিল রাউন্ড, বিনিয়োগকারী পোর্টফোলিও এবং নীতি নথির বিপরীতে বিশ্লেষণ করে প্রমাণ-সমর্থিত সুপারিশ সরবরাহ করে।",
    analyzing: "বিশ্লেষণ প্রক্রিয়াকরণ করা হচ্ছে...",
    missing_info: "তথ্য অনুপস্থিত",
    no_risks_found: "প্রদত্ত তথ্যের ভিত্তিতে কোনও উল্লেখযোগ্য ঝুঁকি সনাক্ত করা যায়নি।",
    analysis_completed: "বিশ্লেষণ সম্পন্ন হয়েছে",
    match: "মিল",
    key_reasons: "প্রধান কারণ",
    q_and_a: "প্রশ্ন এবং উত্তর",
    chat_with_ai: "AI এর সাথে চ্যাট করুন",
    select_context: "প্রসঙ্গের জন্য আপনার স্টার্টআপ নির্বাচন করুন",
    type_message: "আপনার বার্তা টাইপ করুন...",
    no_startups_yet: "এখনও কোনও স্টার্টআপ নেই",
    keep_dreaming: "স্বপ্ন দেখতে থাকুন, বড় ভাবুন!",
    analyzing_fit: "ফিট কারণ বিশ্লেষণ করা হচ্ছে...",
    low: "কম",
    medium: "মাঝারি",
    high: "উচ্চ",
    interface_desc: "আপনার স্থানীয় অভিজ্ঞতা কাস্টমাইজ করুন",
    report_lang_selection_desc: "আপনার গভীর বিশ্লেষণ রিপোর্টের জন্য ডিফল্ট প্রজন্ম ভাষা সেট করুন।",
    did_you_know: "আপনি কি জানেন?",
    did_you_know_desc: "আপনার UI ভাষা পরিবর্তন করলে সমস্ত নেভিগেশন, ত্রুটি বার্তা এবং সিস্টেম ইনসাইটগুলি অবিলম্বে আপডেট হয়।",
    localization_tech: "স্থানীয়করণ প্রযুক্তি",
    localization_tech_desc: "আমাদের RAG মডেলগুলি স্বয়ংক্রিয়ভাবে নির্বাচিত সাংস্কৃতিক প্রেক্ষাপট এবং ভাষাগত সূক্ষ্মতার সাথে প্রমাণ নিষ্কাশন মানিয়ে নেয়।"
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    analyze: "ஆராய்க",
    evidence: "சான்று",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    welcome: "மீண்டும் வருக",
    recent_analysis: "சமீபத்திய பகுப்பாய்வு",
    new_analysis: "புதிய பகுப்பாய்வு",
    funding_fit: "நிதி பொருத்தம்",
    startup_description: "தொடக்க விளக்கம்",
    sector: "துறை",
    funding_stage: "நிதி நிலை",
    geography: "புவியியல்",
    language_settings: "மொழி அமைப்புகள்",
    interface_lang: "இடைமுக மொழி",
    interface_lang_desc: "இந்த மொழி FundingSense இடைமுகம் முழுவதும் பயன்படுத்தப்படும்",
    report_lang: "அறிக்கை மொழி",
    report_lang_desc: "நிதி பகுப்பாய்வு அறிக்கைகள் இயல்பாக இந்த மொழியில் உருவாக்கப்படும்.",
    save_prefs: "விருப்பங்களைச் சேமி",
    about_multilingual: "பன்மொழி ஆதரவு பற்றி",
    about_multilingual_desc: "FundingSense 8 முக்கிய இந்திய மொழிகளை ஆதரிக்கிறது, இது நிறுவனர்கள் மற்றும் முதலீட்டாளர்கள் அவர்கள் விரும்பும் மொழியில் நிதி நுண்ணறிவை அணுக உதவுகிறது.",
    view_all: "அனைத்தையும் காட்டு",
    no_analyses: "எந்த பகுப்பாய்வும் காணப்படவில்லை. இங்கே பார்க்க உங்கள் முதல் பகுப்பாய்வை இயக்கவும்!",
    loading_analyses: "சமீபத்திய பகுப்பாய்வுகள் ஏற்றப்படுகின்றன...",
    loading_evidence: "சான்று ஏற்றப்படுகிறது...",
    just_now: "இப்பொழுது",
    fit_score: "பொருத்தமான ஸ்கோர்",
    confidence: "நம்பிக்கை",
    analyses_run: "பகுப்பாய்வு இயக்கப்பட்டது",
    investors_matched: "முதலீட்டாளர்கள் பொருந்தினர்",
    evidence_points: "சான்று புள்ளிகள்",
    avg_fit_score: "சராசரி பொருத்தமான ஸ்கோர்",
    toggle_theme: "தீமை மாற்றுக",
    search_sources: "மூலங்களைத் தேடு...",
    all_types: "அனைத்து வகை",
    news: "செய்தி",
    policy: "கொள்கை",
    dataset: "தரவு தொகுப்பு",
    used_for: "இதற்காகப் பயன்படுத்தப்பட்டது",
    report_title: "நிதி முடிவு அறிக்கை",
    report_desc: "உங்கள் ஸ்டார்ட்அப்பிற்கான ஆதார ஆதரவு பகுப்பாய்வு",
    why_fits: "ஏன் இது பொருந்துகிறது",
    considerations: "கருத்தில் கொள்ள வேண்டியவை",
    recommended_investors: "பரிந்துரைக்கப்பட்ட முதலீட்டாளர்கள்",
    sources_used: "இந்த பகுப்பாய்விற்கு பயன்படுத்தப்பட்ட ஆதாரங்கள்",
    run_new: "புதிய பகுப்பாய்வை இயக்கு",
    view_evidence: "அனைத்து சான்றுகளையும் காட்டு",
    total_sources: "மொத்த ஆதாரங்கள் காப்பகப்படுத்தப்பட்டன",
    how_it_works: "இது எப்படி வேலை செய்கிறது?",
    how_it_works_desc: "எங்கள் AI உங்கள் தொடக்கத்தை ஆயிரக்கணக்கான வெற்றிகரமான நிதி சுற்றுகள், முதலீட்டாளர் போர்ட்ஃபோலியோக்கள் மற்றும் கொள்கை ஆவணங்களுக்கு எதிராக பகுப்பாய்வு செய்து, சான்றுகள் ஆதரவு பரிந்துரைகளை வழங்குகிறது.",
    analyzing: "பகுப்பாய்வு செயலாக்கப்படுகிறது...",
    missing_info: "தகவல் இல்லை",
    no_risks_found: "வழங்கப்பட்ட தரவுகளின் அடிப்படையில் குறிப்பிடத்தக்க அபாயங்கள் எதுவும் கண்டறியப்படவில்லை.",
    analysis_completed: "பகுப்பாய்வு முடிந்தது",
    match: "பொருத்தம்",
    key_reasons: "முக்கிய காரணங்கள்",
    q_and_a: "கேள்வி பதில்",
    chat_with_ai: "AI உடன் அரட்டையடிக்கவும்",
    select_context: "சூழலுக்கு உங்கள் ஸ்டார்ட்அப்பைத் தேர்ந்தெடுக்கவும்",
    type_message: "உங்கள் செய்தியைத் தட்டச்சு செய்க...",
    no_startups_yet: "இன்னும் ஸ்டார்ட்அப்கள் இல்லை",
    keep_dreaming: "கனவு காணுங்கள், பெரிதாக சிந்தியுங்கள்!",
    analyzing_fit: "பொருத்த காரணிகள் பகுப்பாய்வு செய்யப்படுகின்றன...",
    low: "குறைந்த",
    medium: "நடுத்தர",
    high: "உயர்",
    interface_desc: "உங்கள் உள்ளூர் அனுபவத்தைத் தனிப்பயனாக்குங்கள்",
    report_lang_selection_desc: "உங்கள் ஆழமான பகுப்பாய்வு அறிக்கைகளுக்கான இயல்புநிலை உருவாக்கும் மொழியை அமைக்கவும்.",
    did_you_know: "உங்களுக்கு தெரியுமா?",
    did_you_know_desc: "உங்கள் UI மொழியை மாற்றுவது அனைத்து வழிசெலுத்தல், பிழை செய்திகள் மற்றும் கணினி நுண்ணறிவுகளை உடனடியாகப் புதுப்பிக்கிறது.",
    localization_tech: "உள்ளூர்மயமாக்கல் தொழில்நுட்பம்",
    localization_tech_desc: "எங்கள் RAG மாதிரிகள் தானாகவே தேர்ந்தெடுக்கப்பட்ட கலாச்சார சூழல் மற்றும் மொழியியல் நுணுக்கங்களுக்கு ஏற்ப சான்று பிரித்தெடுப்பை மாற்றியமைக்கின்றன."
  },
  te: {
    dashboard: "డ్యాష్‌బోర్డ్",
    analyze: "విశ్లేషించండి",
    evidence: "రుజువు",
    settings: "సెట్టింగులు",
    logout: "నిష్క్రమించు",
    welcome: "తిరిగి స్వాగతం",
    recent_analysis: "సమీప విశ్లేషణ",
    new_analysis: "కొత్త విశ్లేషణ",
    funding_fit: "నిధుల సరిపోలిక",
    startup_description: "ప్రారంభ వివరణ",
    sector: "రంగం",
    funding_stage: "నిధుల దశ",
    geography: "భౌగోళికం",
    language_settings: "భాషా సెట్టింగులు",
    interface_lang: "ఇంటర్‌ఫేస్ భాష",
    interface_lang_desc: "ఈ భాష ఫండింగ్‌సెన్స్ ఇంటర్‌ఫేస్ అంతటా ఉపయోగించబడుతుంది",
    report_lang: "నివేదిక భాష",
    report_lang_desc: "నిధుల విశ్లేషణ నివేదికలు డిఫాల్ట్‌గా ఈ భాషలో ఉత్పత్తి చేయబడతాయి.",
    save_prefs: "ప్రాధాన్యతలను సేవ్ చేయండి",
    about_multilingual: "బహుభాషా మద్దతు గురించి",
    about_multilingual_desc: "ఫండింగ్‌సెన్స్ 8 ప్రధాన భారతీయ భాషలకు మద్దతు ఇస్తుంది, వ్యవస్థాపకులు మరియు పెట్టుబడిదారులు వారి ఇష్టపడే భాషలో నిధుల మేధస్సును పొందేందుకు వీలు కల్పిస్తుంది.",
    view_all: "అన్నింటినీ చూడండి",
    no_analyses: "విశ్లేషణలు కనుగొనబడలేదు. ఇక్కడ చూడడానికి మీ మొదటి విశ్లేషణను అమలు చేయండి!",
    loading_analyses: "సమీప విశ్లేషణలు లోడ్ అవుతున్నాయి...",
    loading_evidence: "రుజువు లోడ్ అవుతోంది...",
    just_now: "ఇప్పుడే",
    fit_score: "సరిపోలిక స్కోర్",
    confidence: "విశ్వాసం",
    analyses_run: "విశ్లేషణలు అమలు చేయబడ్డాయి",
    investors_matched: "పెట్టుబడిదారులు సరిపోలారు",
    evidence_points: "రుజువు పాయింట్లు",
    avg_fit_score: "సగటు సరిపోలిక స్కోర్",
    toggle_theme: "థీమ్‌ను టోగుల్ చేయండి",
    search_sources: "మూలాలను వెతకండి...",
    all_types: "అన్ని రకాలు",
    news: "వార్తలు",
    policy: "విధానం",
    dataset: "డేటాసెట్",
    used_for: "దీని కోసం ఉపయోగించబడింది",
    report_title: "నిధుల నిర్ణయ నివేదిక",
    report_desc: "మీ స్టార్టప్ కోసం రుజువు-మద్దతు విశ్లేషణ",
    why_fits: "ఇది ఎందుకు సరిపోతుంది",
    considerations: "పరిశీలనలు",
    recommended_investors: "సిఫార్సు చేయబడిన పెట్టుబడిదారులు",
    sources_used: "ఈ విశ్లేషణకు ఉపయోగించిన మూలాలు",
    run_new: "కొత్త విశ్లేషణను అమలు చేయండి",
    view_evidence: "అన్ని రుజువులను చూడండి",
    total_sources: "మొత్తం మూలాలు ఆర్కైవ్ చేయబడ్డాయి",
    how_it_works: "ఇది ఎలా పని చేస్తుంది?",
    how_it_works_desc: "మా AI మీ స్టార్టప్‌ను వేలాది విజయవంతమైన నిధుల రౌండ్‌లు, పెట్టుబడిదారుల పోర్ట్‌ఫోలియోలు మరియు విధాన పత్రాలకు వ్యతిరేకంగా విశ్లేషిస్తుంది మరియు రుజువు-మద్దతు సిఫార్సులను అందిస్తుంది.",
    analyzing: "విశ్లేషణ ప్రాసెస్ చేయబడుతోంది...",
    missing_info: "సమాచారం లేదు",
    no_risks_found: "అందించిన డేటా ఆధారంగా గుర్తించదగిన ప్రమాదాలు కనుగొనబడలేదు.",
    analysis_completed: "విశ్లేషణ పూర్తయింది",
    match: "సరిపోలిక",
    key_reasons: "ముఖ్య కారణాలు",
    q_and_a: "ప్రశ్నోత్తరాలు",
    chat_with_ai: "AIతో చాట్ చేయండి",
    select_context: "సందర్భం కోసం మీ స్టార్టప్‌ని ఎంచుకోండి",
    type_message: "మీ సందేశాన్ని టైప్ చేయండి...",
    no_startups_yet: "ఇంకా స్టార్టప్‌లు లేవు",
    keep_dreaming: "కలలు కంటూనే ఉండండి, పెద్దగా ఆలోచించండి!",
    analyzing_fit: "సరిపోలిక కారకాలను విశ్లేషిస్తున్నారు...",
    low: "తక్కువ",
    medium: "మధ్యస్థ",
    high: "ఎక్కువ",
    interface_desc: "మీ స్థానిక అనుభవాన్ని అనుకూలీకరించండి",
    report_lang_selection_desc: "మీ లోతైన విశ్లేషణ నివేదికల కోసం డిఫాల్ట్ ఉత్పత్తి భాషను సెట్ చేయండి.",
    did_you_know: "మీకు తెలుసా?",
    did_you_know_desc: "మీ UI భాషను మార్చడం వలన అన్ని నావిగేషన్, లోప సందేశాలు మరియు సిస్టమ్ అంతర్దృష్టులు తక్షణమే నవీకరించబడతాయి.",
    localization_tech: "స్థానికీకరణ సాంకేతికత",
    localization_tech_desc: "మా RAG నమూనాలు స్వయంచాలకంగా ఎంచుకున్న సాంస్కృతిక సందర్భం మరియు భాషాపరమైన సూక్ష్మ నైపుణ్యాలకు సాక్ష్యం వెలికితీతను స్వీకరిస్తాయి."
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    analyze: "विश्लेषण करा",
    evidence: "पुरावा",
    settings: "सेटिंग्ज",
    logout: "लॉग आउट",
    welcome: "परत स्वागत आहे",
    recent_analysis: "अलीकडील विश्लेषण",
    new_analysis: "नवीन विश्लेषण",
    funding_fit: "निधी जुळवणी",
    startup_description: "स्टार्टअप वर्णन",
    sector: "क्षेत्र",
    funding_stage: "निधी टप्पा",
    geography: "भूगोल",
    language_settings: "भाषा सेटिंग्ज",
    interface_lang: "इंटरफेस भाषा",
    interface_lang_desc: "ही भाषा FundingSense इंटरफेसमध्ये वापरली जाईल",
    report_lang: "अहवाल भाषा",
    report_lang_desc: "निधी विश्लेषण अहवाल डीफॉल्टनुसार या भाषेत तयार केले जातील.",
    save_prefs: "प्राधान्ये जतन करा",
    about_multilingual: "बहुभाषिक समर्थनाबद्दल",
    about_multilingual_desc: "FundingSense 8 प्रमुख भारतीय भाषांना समर्थन देते, ज्यामुळे संस्थापक आणि गुंतवणूकदारांना त्यांच्या आवडीच्या भाषेत निधी बुद्धिमत्ता मिळवता येते.",
    view_all: "सर्व पहा",
    no_analyses: "कोणतेही विश्लेषण आढळले नाही. ते पाहण्यासाठी आपले पहिले विश्लेषण चालवा!",
    loading_analyses: "अलीकडील विश्लेषण लोड करत आहे...",
    loading_evidence: "पुरावा लोड करत आहे...",
    just_now: "आत्ताच",
    fit_score: "जुळवणी गुण",
    confidence: "आत्मविश्वास",
    analyses_run: "विश्लेषण चालवले",
    investors_matched: "गुंतवणूकदार जुळले",
    evidence_points: "पुरावा गुण",
    avg_fit_score: "सरासरी जुळवणी गुण",
    toggle_theme: "थीम टॉगल करा",
    search_sources: "स्रोत शोधा...",
    all_types: "सर्व प्रकार",
    news: "बातम्या",
    policy: "धोरण",
    dataset: "डेटासेट",
    used_for: "यासाठी वापरले",
    report_title: "निधी निर्णय अहवाल",
    report_desc: "तुमच्या स्टार्टअपसाठी पुरावा-आधारित विश्लेषण",
    why_fits: "हे का जुळते",
    considerations: "विचार",
    recommended_investors: "शिफारस केलेले गुंतवणूकदार",
    sources_used: "या विश्लेषणासाठी वापरलेले स्रोत",
    run_new: "नवीन विश्लेषण चालवा",
    view_evidence: "सर्व पुरावे पहा",
    total_sources: "एकूण स्रोत संग्रहित",
    how_it_works: "हे कसे कार्य करते?",
    how_it_works_desc: "आमचे AI तुमच्या स्टार्टअपचे हजारो यशस्वी निधी फेऱ्या, गुंतवणूकदार पोर्टफोलिओ और धोरण दस्तऐवाजांच्या आधारे विश्लेषण करते आणि पुरावा-आधारित शिफारसी प्रदान करते.",
    analyzing: "विश्लेषण प्रक्रिया करत आहे...",
    missing_info: "माहिती गहाळ आहे",
    no_risks_found: "प्रदान केलेल्या डेटाच्या आधारावर कोणतेही महत्त्वपूर्ण धोके आढळले नाहीत.",
    analysis_completed: "विश्लेषण पूर्ण झाले",
    match: "जुळवणी",
    key_reasons: "मुख्य कारणे",
    q_and_a: "प्रश्न आणि उत्तरे",
    chat_with_ai: "AI सह चॅट करा",
    select_context: "संदर्भासाठी तुमचा स्टार्टअप निवडा",
    type_message: "तुमचा संदेश टाइप करा...",
    no_startups_yet: "अद्याप कोणतेही स्टार्टअप नाही",
    keep_dreaming: "स्वप्ने पाहत रहा, मोठा विचार करा!",
    analyzing_fit: "जुळवणी घटकांचे विश्लेषण करत आहे...",
    low: "कमी",
    medium: "मध्यम",
    high: "उच्च",
    interface_desc: "तुमचा स्थानिक अनुभव सानुकूलित करा",
    report_lang_selection_desc: "तुमच्या सखोल विश्लेषणाच्या अहवालांसाठी डीफॉल्ट जनरेशन भाषा सेट करा.",
    did_you_know: "तुम्हाला माहित आहे का?",
    did_you_know_desc: "तुमची UI भाषा बदलल्याने सर्व नेव्हिगेशन, त्रुटी संदेश आणि सिस्टम अंतर्दृष्टी त्वरित अद्यतनित होतात.",
    localization_tech: "स्थानिकीकरण तंत्रज्ञान",
    localization_tech_desc: "आमची RAG मॉडेल निवडलेल्या सांस्कृतिक संदर्भानुसार आणि भाषिक सूक्ष्मतानुसार पुरावा काढण्याची प्रक्रिया आपोआप जुळवून घेतात."
  },
  gu: {
    dashboard: "ડેશબોર્ડ",
    analyze: "વિશ્લેષણ કરો",
    evidence: "પુરાવા",
    settings: "સેટિંગ્સ",
    logout: "લૉગ આઉટ",
    welcome: "પાછા સ્વાગત છે",
    recent_analysis: "તાજેતરનું વિશ્લેષણ",
    new_analysis: "નવું વિશ્લેષણ",
    funding_fit: "ફંડિંગ ફિટ",
    startup_description: "સ્ટાર્ટઅપ વર્ણન",
    sector: "ક્ષેત્ર",
    funding_stage: "ફંડિંગ સ્ટેજ",
    geography: "ભૂગોળ",
    language_settings: "ભાષા સેટિંગ્સ",
    interface_lang: "ઇન્ટરફેસ ભાષા",
    interface_lang_desc: "આ ભાષાનો ઉપયોગ ફંડિંગસેન્સ ઇન્ટરફેસમાં કરવામાં આવશે",
    report_lang: "અહેવાલ ભાષા",
    report_lang_desc: "ફંડિંગ વિશ્લેષણ અહેવાલો આ ભાષામાં ડિફૉલ્ટ રૂપે જનરેટ થશે.",
    save_prefs: "પસંદગીઓ સાચવો",
    about_multilingual: "બહુભાષી સપોર્ટ વિશે",
    about_multilingual_desc: "ફંડિંગસેન્સ 8 મુખ્ય ભારતીય ભાષાઓને સપોર્ટ કરે છે, જે સ્થાપકો અને રોકાણકારોને તેમની પસંદગીની ભાષામાં ફંડિંગ ઇન્ટેલિજન્સને એક્સેસ કરવા સક્ષમ બનાવે છે.",
    view_all: "બધું જુઓ",
    no_analyses: "કોઈ વિશ્લેષણ મળ્યું નથી. તેને જોવા માટે તમારું પ્રથમ વિશ્લેષણ ચલાવો!",
    loading_analyses: "તાજેતરના વિશ્લેષણો લોડ થઈ રહ્યા છે...",
    loading_evidence: "પુરાવા લોડ થઈ રહ્યા છે...",
    just_now: "હમણાં જ",
    fit_score: "ફિટ સ્કોર",
    confidence: "આત્મવિશ્વાસ",
    analyses_run: "વિશ્લેષણો ચલાવવામાં આવ્યા",
    investors_matched: "રોકાણકારો મેળ ખાતા",
    evidence_points: "પુરાવા પોઇન્ટ્સ",
    avg_fit_score: "સરેરાશ ફિટ સ્કોર",
    toggle_theme: "થીમ ટૉગલ કરો",
    search_sources: "સ્ત્રોતો શોધો...",
    all_types: "બધા પ્રકારો",
    news: "સમાચાર",
    policy: "નીતિ",
    dataset: "ડેટાસેટ",
    used_for: "માટે વપરાયેલ",
    report_title: "ફંડિંગ નિર્ણય અહેવાલ",
    report_desc: "તમારું સ્ટાર્ટઅપ માટે પુરાવા-સમર્થિત વિશ્લેષણ",
    why_fits: "આ શા માટે બંધબેસે છે",
    considerations: "વિચારો",
    recommended_investors: "ભલામણ કરેલ રોકાણકારો",
    sources_used: "આ વિશ્લેષણ માટે વપરાયેલ સ્ત્રોતો",
    run_new: "નવું વિશ્લેષણ ચલાવો",
    view_evidence: "બધા પુરાવા જુઓ",
    total_sources: "કુલ સ્ત્રોતો આર્કાઇવ કરેલા છે",
    how_it_works: "આ કેવી રીતે કામ કરે છે?",
    how_it_works_desc: "અમારું AI હજારો સફળ ફંડિંગ રાઉન્ડ, રોકાણકાર પોર્ટફોલિયો અને નીતિ દસ્તાવેજો સામે તમારા સ્ટાર્ટઅપનું વિશ્લેષણ કરે છે અને પુરાવા-સમર્થિત ભલામણો પૂરી પાડે છે.",
    analyzing: "વિશ્લેષણની પ્રક્રિયા ચાલી રહી છે...",
    missing_info: "માહિતી ખૂટે છે",
    no_risks_found: "આપેલા ડેટાના આધારે કોઈ નોંધપાત્ર જોખમો મળ્યા નથી.",
    analysis_completed: "વિશ્લેષણ પૂર્ણ થયું",
    match: "મેળ",
    key_reasons: "મુખ્ય કારણો",
    q_and_a: "પ્રશ્ન અને ઉત્તર",
    chat_with_ai: "AI સાથે ચેટ કરો",
    select_context: "સંદર્ભ માટે તમારો સ્ટાર્ટઅપ પસંદ કરો",
    type_message: "તમારો સંદેશ લખો...",
    no_startups_yet: "હજી સુધી કોઈ સ્ટાર્ટઅપ નથી",
    keep_dreaming: "સ્વપ્ન જોતા રહો, મોટું વિચારો!",
    analyzing_fit: "ફિટ પરિબળોનું વિશ્લેષણ કરી રહ્યા છીએ...",
    low: "ઓછી",
    medium: "મધ્યમ",
    high: "ઉચ્ચ",
    interface_desc: "તમારા સ્થાનિક અનુભવને કસ્ટમાઇઝ કરો",
    report_lang_selection_desc: "તમારા ઊંડા વિશ્લેષણ અહેવાલો માટે ડિફૉલ્ટ જનરેશન ભાષા સેટ કરો.",
    did_you_know: "શું તમે જાણો છો?",
    did_you_know_desc: "તમારી UI ભાષા બદલવાથી તમામ નેવિગેશન, ભૂલ સંદેશાઓ અને સિસ્ટમ આંતરદૃષ્ટિ તાત્કાલિક અપડેટ થાય છે.",
    localization_tech: "સ્થાનિકીકરણ તકનીક",
    localization_tech_desc: "અમારા RAG મોડેલો પસંદ કરેલ સાંસ્કૃતિક સંદર્ભ અને ભાષાકીય ઘોંઘાટને આપમેળે પુરાવા નિષ્કર્ષણને અનુરૂપ બનાવે છે."
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    analyze: "ವಿಶ್ಲೇಷಿಸಿ",
    evidence: "ಪುರಾವೆ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    logout: "ಲಾಗ್ ಔಟ್",
    welcome: "ಮರಳಿ ಸ್ವಾಗತ",
    recent_analysis: "ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆ",
    new_analysis: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ",
    funding_fit: "ನಿಧಿಯ ಹೊಂದಾಣಿಕೆ",
    startup_description: "ಸ್ಟಾರ್ಟ್ಅಪ್ ವಿವರಣೆ",
    sector: "ಕ್ಷೇತ್ರ",
    funding_stage: "ನಿಧಿಯ ಹಂತ",
    geography: "ಭೂಗೋಳ",
    language_settings: "ಭಾಷಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    interface_lang: "ಇಂಟರ್ಫೇಸ್ ಭಾಷೆ",
    interface_lang_desc: "ಈ ಭಾಷೆಯನ್ನು ಫಂಡಿಂಗ್‌ಸೆನ್ಸ್ ಇಂಟರ್ಫೇಸ್‌ನಾದ್ಯಂತ ಬಳಸಲಾಗುತ್ತದೆ",
    report_lang: "ವರದಿ ಭಾಷೆ",
    report_lang_desc: "ನಿಧಿಯ ವಿಶ್ಲೇಷಣಾ ವರದಿಗಳನ್ನು ಪೂರ್ವನಿಯೋಜಿತವಾಗಿ ಈ ಭಾಷೆಯಲ್ಲಿ ಉತ್ಪಾದಿಸಲಾಗುತ್ತದೆ.",
    save_prefs: "ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ",
    about_multilingual: "ಬಹುಭಾಷಾ ಬೆಂಬಲದ ಬಗ್ಗೆ",
    about_multilingual_desc: "ಫಂಡಿಂಗ್‌ಸೆನ್ಸ್ 8 ಪ್ರಮುಖ ಭಾರತೀಯ ಭಾಷೆಗಳನ್ನು ಬೆಂಬಲಿಸುತ್ತದೆ, ಇದು ಸಂಸ್ಥಾಪಕರು ಮತ್ತು ಹೂಡಿಕೆದಾರರಿಗೆ ಅವರು ಆದ್ಯತೆ ನೀಡುವ ಭಾಷೆಯಲ್ಲಿ ನಿಧಿಯ ಬುದ್ಧಿವಂತಿಕೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ಅನುವು ಮಾಡಿಕೊಡುತ್ತದೆ.",
    view_all: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    no_analyses: "ಯಾವುದೇ ವಿಶ್ಲೇಷಣೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಅದನ್ನು ನೋಡಲು ನಿಮ್ಮ ಮೊದಲ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಚಲಾಯಿಸಿ!",
    loading_analyses: "ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    loading_evidence: "ಪುರಾವೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    just_now: "ಈಗ ತಾನೇ",
    fit_score: "ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್",
    confidence: "ವಿಶ್ವಾಸ",
    analyses_run: "ವಿಶ್ಲೇಷಣೆಗಳು ಚಾಲನೆಯಲ್ಲಿವೆ",
    investors_matched: "ಹೂಡಿಕೆದಾರರು ಹೊಂದಾಣಿಕೆಯಾಗಿದ್ದಾರೆ",
    evidence_points: "ಪುರಾವೆ ಅಂಕಗಳು",
    avg_fit_score: "ಸರಾಸರಿ ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್",
    toggle_theme: "ಥೀಮ್ ಟಾಗಲ್ ಮಾಡಿ",
    search_sources: "ಮೂಲಗಳನ್ನು ಹುಡುಕಿ...",
    all_types: "ಎಲ್ಲಾ ವಿಧಗಳು",
    news: "ಸುದ್ದಿ",
    policy: "ನೀತಿ",
    dataset: "ಡೇಟಾಸೆಟ್",
    used_for: "ಇದಕ್ಕಾಗಿ ಬಳಸಲಾಗಿದೆ",
    report_title: "ನಿಧಿ ನಿರ್ಧಾರ ವರದಿ",
    report_desc: "ನಿಮ್ಮ ಸ್ಟಾರ್ಟ್ಅಪ್‌ಗಾಗಿ ಪುರಾವೆ-ಬೆಂಬಲಿತ ವಿಶ್ಲೇಷಣೆ",
    why_fits: "ಇದು ಏಕೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ",
    considerations: "ಪರಿಗಣನೆಗಳು",
    recommended_investors: "ಶಿಫಾರಸು ಮಾಡಲಾದ ಹೂಡಿಕೆದಾರರು",
    sources_used: "ಈ ವಿಶ್ಲೇಷಣೆಗೆ ಬಳಸಲಾದ ಮೂಲಗಳು",
    run_new: "ಹೊಸ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಚಲಾಯಿಸಿ",
    view_evidence: "ಎಲ್ಲಾ ಪುರಾವೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    total_sources: "ಒಟ್ಟು ಮೂಲಗಳನ್ನು ಆರ್ಕೈವ್ ಮಾಡಲಾಗಿದೆ",
    how_it_works: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ?",
    how_it_works_desc: "ನಮ್ಮ AI ನಿಮ್ಮ ಸ್ಟಾರ್ಟ್ಅಪ್ ಅನ್ನು ಸಾವಿರಾರು ಯಶಸ್ವಿ ನಿಧಿಯ ಸುತ್ತುಗಳು, ಹೂಡಿಕೆದಾರರ ಪೋರ್ಟ್ಫೋಲಿಯೊಗಳು ಮತ್ತು ನೀತಿ ದಾಖಲೆಗಳ ವಿರುದ್ಧ ವಿಶ್ಲೇಷಿಸುತ್ತದೆ ಮತ್ತು ಪುರಾವೆ-ಬೆಂಬಲಿತ ಶಿಫಾರಸುಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ.",
    analyzing: "ವಿಶ್ಲೇಷಣೆಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    missing_info: "ಮಾಹಿತಿ ಕಾಣೆಯಾಗಿದೆ",
    no_risks_found: "ಒದಗಿಸಿದ ಡೇಟಾದ ಆಧಾರದ ಮೇಲೆ ಯಾವುದೇ ಗಮನಾರ್ಹ ಅಪಾಯಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    analysis_completed: "ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ",
    match: "ಹೊಂದಿಕೆ",
    key_reasons: "ಪ್ರಮುಖ ಕಾರಣಗಳು",
    q_and_a: "ಪ್ರಶ್ನೋತ್ತರ",
    chat_with_ai: "AI ನೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    select_context: "ಸಂದರ್ಭಕ್ಕಾಗಿ ನಿಮ್ಮ ಸ್ಟಾರ್ಟ್ಅಪ್ ಅನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    type_message: "ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    no_startups_yet: "ಇನ್ನೂ ಯಾವುದೇ ಸ್ಟಾರ್ಟ್ಅಪ್‌ಗಳಿಲ್ಲ",
    keep_dreaming: "ಕನಸು ಕಾಣುತ್ತಿರಿ, ದೊಡ್ಡದಾಗಿ ಯೋಚಿಸಿ!",
    analyzing_fit: "ಹೊಂದಾಣಿಕೆ ಅಂಶಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    low: "ಕಡಿಮೆ",
    medium: "ಮಧ್ಯಮ",
    high: "ಹೆಚ್ಚು",
    interface_desc: "ನಿಮ್ಮ ಸ್ಥಳೀಯ ಅನುಭವವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ",
    report_lang_selection_desc: "ನಿಮ್ಮ ಆಳವಾದ ವಿಶ್ಲೇಷಣೆ ವರದಿಗಳಿಗಾಗಿ ಡೀಫಾಲ್ಟ್ ಉತ್ಪಾದನಾ ಭಾಷೆಯನ್ನು ಹೊಂದಿಸಿ.",
    did_you_know: "ನಿಮಗೆ ಗೊತ್ತಾ?",
    did_you_know_desc: "ನಿಮ್ಮ UI ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸುವುದರಿಂದ ಎಲ್ಲಾ ನ್ಯಾವಿಗೇಷನ್, ದೋಷ ಸಂದೇಶಗಳು ಮತ್ತು ಸಿಸ್ಟಮ್ ಒಳನೋಟಗಳನ್ನು ತಕ್ಷಣವೇ ನವೀಕರಿಸಲಾಗುತ್ತದೆ.",
    localization_tech: "ಸ್ಥಳೀಕರಣ ತಂತ್ರಜ್ಞಾನ",
    localization_tech_desc: "ನಮ್ಮ RAG ಮಾದರಿಗಳು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಆಯ್ದ ಸಾಂಸ್ಕೃತಿಕ ಸನ್ನಿವೇಶ ಮತ್ತು ಭಾಷಾ ಸೂಕ್ಷ್ಮ ವ್ಯತ್ಯಾಸಗಳಿಗೆ ಪುರಾವೆ ಹೊರತೆಗೆಯುವಿಕೆಯನ್ನು ಹೊಂದಿಕೊಳ್ಳುತ್ತವೆ."
  },
  en: {
    dashboard: "Dashboard",
    analyze: "Analyze",
    evidence: "Evidence",
    settings: "Settings",
    logout: "Logout",
    welcome: "Welcome back",
    recent_analysis: "Recent Analysis",
    new_analysis: "New Analysis",
    funding_fit: "Funding Fit",
    startup_description: "Startup Description",
    sector: "Sector",
    funding_stage: "Funding Stage",
    geography: "Geography",
    language_settings: "Language Settings",
    interface_lang: "Interface Language",
    interface_lang_desc: "This language will be used throughout the FundingSense interface",
    report_lang: "Report Language",
    report_lang_desc: "Funding analysis reports will be generated in this language by default.",
    save_prefs: "Save Preferences",
    about_multilingual: "About Multilingual Support",
    about_multilingual_desc: "FundingSense supports 8 major Indian languages, enabling founders and investors to access funding intelligence in their preferred language.",
    view_all: "View all",
    no_analyses: "No analyses found. Run your first analysis to see it here!",
    loading_analyses: "Loading recent analyses...",
    loading_evidence: "Loading evidence...",
    just_now: "Just now",
    fit_score: "Fit Score",
    confidence: "Confidence",
    analyses_run: "Analyses Run",
    investors_matched: "Investors Matched",
    evidence_points: "Evidence Points",
    avg_fit_score: "Avg. Fit Score",
    toggle_theme: "Toggle Theme",
    search_sources: "Search sources...",
    all_types: "All Types",
    news: "News",
    policy: "Policy",
    dataset: "Dataset",
    used_for: "Used for",
    report_title: "Funding Decision Report",
    report_desc: "Evidence-backed analysis for your startup",
    why_fits: "Why This Fits",
    considerations: "Considerations",
    recommended_investors: "Recommended Investors",
    sources_used: "sources used for this analysis",
    run_new: "Run New Analysis",
    view_evidence: "View All Evidence",
    total_sources: "Total Sources Archived",
    how_it_works: "How does this work?",
    how_it_works_desc: "Our AI analyzes your startup against thousands of successful funding rounds, investor portfolios, and policy documents to provide evidence-backed recommendations.",
    analyzing: "Processing analysis...",
    missing_info: "Missing Information",
    no_risks_found: "No significant risks identified based on the provided data.",
    analysis_completed: "Analysis Completed",
    match: "Match",
    key_reasons: "Key Reasons",
    q_and_a: "Q & A",
    chat_with_ai: "Chat with AI",
    select_context: "Select your startup for context",
    type_message: "Type your message...",
    no_startups_yet: "No startups yet",
    keep_dreaming: "Keep dreaming, think big!",
    analyzing_fit: "Analyzing fit factors...",
    low: "Low",
    medium: "Medium",
    high: "High",
    interface_desc: "Customize your localized experience",
    report_lang_selection_desc: "Set the default generation language for your deep analysis reports.",
    did_you_know: "Did you know?",
    did_you_know_desc: "Changing your UI language updates all navigation, error messages, and system insights instantly.",
    localization_tech: "Localization Tech",
    localization_tech_desc: "Our RAG models automatically adapt evidence extraction to the selected cultural context and linguistic nuances."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en");
  const [userId, setUserId] = useState<string | null>(null);

  useEffect(() => {
    // Sync language with current session
    const syncLanguage = (user: any) => {
      const currentUserId = user?.id || null;
      setUserId(currentUserId);

      const key = currentUserId ? `uiLanguage_${currentUserId}` : "uiLanguage_guest";
      const saved = localStorage.getItem(key) || "en";
      setLanguageState(saved as Language);
    };

    // Initial session check
    supabase.auth.getSession().then(({ data: { session } }) => {
      syncLanguage(session?.user);
    });

    // Listen for auth state changes (login/logout)
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      syncLanguage(session?.user);
    });

    return () => subscription.unsubscribe();
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    const key = userId ? `uiLanguage_${userId}` : "uiLanguage_guest";
    localStorage.setItem(key, lang);
    // We also update the general one for the landing page transition
    localStorage.setItem("uiLanguage", lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;

    // Sync Google Translate engine if available
    const syncGoogleTranslate = () => {
      const googleCombo = document.querySelector('.goog-te-combo') as HTMLSelectElement;
      if (googleCombo) {
        googleCombo.value = language;
        googleCombo.dispatchEvent(new Event('change'));
      }
    };

    // Small delay to ensure Google script has loaded and rendered the combo
    const timer = setTimeout(syncGoogleTranslate, 1500);
    return () => clearTimeout(timer);
  }, [language]);

  const t = (key: string) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
