import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "hi" | "bn" | "ta" | "te" | "mr" | "gu" | "kn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    analyze: "Analyze",
    evidence: "Evidence",
    settings: "Settings",
    logout: "Logout",
    welcome: "Welcome back",
    recent_analysis: "Recent Analysis",
    new_analysis: "New Analysis",
    funding_fit: "Funding Fit",
    startup_description: "Startup Description",
    sector: "Sector",
    funding_stage: "Funding Stage",
    geography: "Geography",
    language_settings: "Language Settings",
    interface_lang: "Interface Language",
    interface_lang_desc: "This language will be used throughout the FundingSense interface",
    report_lang: "Report Language",
    report_lang_desc: "Funding analysis reports will be generated in this language by default.",
    save_prefs: "Save Preferences",
    about_multilingual: "About Multilingual Support",
    about_multilingual_desc: "FundingSense supports 8 major Indian languages, enabling founders and investors to access funding intelligence in their preferred language.",
    view_all: "View all",
    no_analyses: "No analyses found. Run your first analysis to see it here!",
    loading_analyses: "Loading recent analyses...",
    loading_evidence: "Loading evidence...",
    just_now: "Just now",
    fit_score: "Fit Score",
    confidence: "Confidence",
    analyses_run: "Analyses Run",
    investors_matched: "Investors Matched",
    evidence_points: "Evidence Points",
    avg_fit_score: "Avg. Fit Score",
    toggle_theme: "Toggle Theme",
    search_sources: "Search sources...",
    all_types: "All Types",
    news: "News",
    policy: "Policy",
    dataset: "Dataset",
    used_for: "Used for",
    report_title: "Funding Decision Report",
    report_desc: "Evidence-backed analysis for your startup",
    why_fits: "Why This Fits",
    considerations: "Considerations",
    recommended_investors: "Recommended Investors",
    sources_used: "sources used for this analysis",
    run_new: "Run New Analysis",
    view_evidence: "View All Evidence",
    total_sources: "Total Sources Archived",
    how_it_works: "How does this work?",
    how_it_works_desc: "Our AI analyzes your startup against thousands of successful funding rounds, investor portfolios, and policy documents to provide evidence-backed recommendations.",
    analyzing: "Processing analysis...",
    missing_info: "Missing Information",
    no_risks_found: "No significant risks or misalignments identified based on the provided data.",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    analyze: "विश्लेषण",
    evidence: "प्रमाण",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    welcome: "वापसी पर स्वागत है",
    recent_analysis: "हालिया विश्लेषण",
    new_analysis: "नया विश्लेषण",
    funding_fit: "फंडिंग फिट",
    startup_description: "स्टार्टअप विवरण",
    sector: "क्षेत्र",
    funding_stage: "फंडिंग चरण",
    geography: "भूगोल",
    language_settings: "भाषा सेटिंग्स",
    interface_lang: "इंटरफ़ेस भाषा",
    interface_lang_desc: "यह भाषा पूरे फंडिंगसेंस इंटरफ़ेस में उपयोग की जाएगी",
    report_lang: "रिपोर्ट भाषा",
    report_lang_desc: "फंडिंग विश्लेषण रिपोर्ट डिफ़ॉल्ट रूप से इस भाषा में तैयार की जाएगी।",
    save_prefs: "प्राथमिकताएं सहेजें",
    about_multilingual: "बहुभाषी सहयोग के बारे में",
    about_multilingual_desc: "फंडिंगसेंस 8 प्रमुख भारतीय भाषाओं का समर्थन करता है, जिससे संस्थापकों और निवेशकों को उनकी पसंदीदा भाषा में फंडिंग इंटेलिजेंस प्राप्त करने में मदद मिलती है।",
    view_all: "सभी देखें",
    no_analyses: "कोई विश्लेषण नहीं मिला। अपना पहला विश्लेषण यहाँ देखने के लिए चलाएँ!",
    loading_analyses: "हालिया विश्लेषण लोड हो रहा है...",
    loading_evidence: "प्रमाण लोड हो रहा है...",
    just_now: "अभी-अभी",
    fit_score: "फिट स्कोर",
    confidence: "विशवास",
    analyses_run: "किए गए विश्लेषण",
    investors_matched: "मिलान किए गए निवेशक",
    evidence_points: "प्रमाण बिंदु",
    avg_fit_score: "औसत फिट स्कोर",
    toggle_theme: "थीम बदलें",
    search_sources: "स्रोतों की खोज करें...",
    all_types: "सभी प्रकार",
    news: "समाचार",
    policy: "नीति",
    dataset: "डेटासेट",
    used_for: "उपयोग किया गया:",
    report_title: "फंडिंग निर्णय रिपोर्ट",
    report_desc: "आपके स्टार्टअप के लिए प्रमाण-आधारित विश्लेषण",
    why_fits: "यह क्यों फिट बैठता है",
    considerations: "विचारणीय बिंदु",
    recommended_investors: "अनुशंसित निवेशक",
    sources_used: "इस विश्लेषण के लिए उपयोग किए गए स्रोत",
    run_new: "नया विश्लेषण चलाएँ",
    view_evidence: "सभी प्रमाण देखें",
    missing_info: "अधूरी जानकारी",
    no_risks_found: "प्रदान किए गए डेटा के आधार पर कोई महत्वपूर्ण जोखिम या गलत संरेखण नहीं पाया गया।",
    analysis_completed: "विश्लेषण पूरा हुआ",
    match: "मैच",
    key_reasons: "प्रमुख कारण",
    analyzing_fit: "फिट कारकों का विश्लेषण किया जा रहा है...",
    how_it_works: "यह कैसे काम करता है",
    how_it_works_desc: "हमारा AI आपके स्टार्टअप क्षेत्र, चरण और भौगोलिक स्थिति के आधार पर हजारों निवेशकों और बाजार डेटा बिंदुओं का विश्लेषण करता है ताकि आपको सबसे सटीक सिफारिशें मिल सकें।",
    analyzing: "विश्लेषण किया जा रहा है...",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    analyze: "বিশ্লেষণ",
    evidence: "প্রমাণ",
    settings: "সেটিংস",
    logout: "লগআউট",
    welcome: "স্বাগত",
    recent_analysis: "সাম্প্রতিক বিশ্লেষণ",
    new_analysis: "নতুন বিশ্লেষণ",
    funding_fit: "ফান্ডিং ফিট",
    startup_description: "স্টার্টআপ বিবরণ",
    sector: "সেক্টর",
    funding_stage: "ফান্ডিং পর্যায়",
    geography: "ভৌগোলিক অবস্থান",
    language_settings: "ভাষা সেটিংস",
    interface_lang: "ইন্টারফেস ভাষা",
    interface_lang_desc: "এই ভাষাটি পুরো ফান্ডিংসেন্স ইন্টারফেসে ব্যবহৃত হবে",
    report_lang: "রিপোর্ট ভাষা",
    report_lang_desc: "ফান্ডিং বিশ্লেষণ রিপোর্ট ডিফল্টরূপে এই ভাষায় তৈরি করা হবে।",
    save_prefs: "পছন্দগুলি সংরক্ষণ করুন",
    about_multilingual: "বহুভাষিক সমর্থন সম্পর্কে",
    about_multilingual_desc: "ফান্ডিংসেন্স ৮টি প্রধান ভারতীয় ভাষা সমর্থন করে, যা প্রতিষ্ঠাতা এবং বিনিয়োগকারীদের তাদের পছন্দের ভাষায় ফান্ডিং ইন্টেলিজেন্ট অ্যাক্সেস করতে সক্ষম করে।",
    view_all: "সব দেখুন",
    no_analyses: "কোনো বিশ্লেষণ পাওয়া যায়নি। আপনার প্রথম বিশ্লেষণ দেখতে এখানে ক্লিক করুন!",
    loading_analyses: "সাম্প্রতিক বিশ্লেষণ লোড হচ্ছে...",
    loading_evidence: "প্রমাণ লোড হচ্ছে...",
    just_now: "এইমাত্র",
    fit_score: "ফিট স্কোর",
    confidence: "আত্মবিশ্বাস",
    analyses_run: "বিশ্লেষণ চালানো হয়েছে",
    investors_matched: "বিনিয়োগকারী মিলেছে",
    evidence_points: "প্রমাণ পয়েন্ট",
    avg_fit_score: "গড় ফিট স্কোর",
    toggle_theme: "থিম পরিবর্তন করুন",
    search_sources: "উত্স অনুসন্ধান করুন...",
    all_types: "সব ধরন",
    news: "খবর",
    policy: "নীতি",
    dataset: "ডেটাসেট",
    used_for: "ব্যবহৃত",
    report_title: "ফান্ডিং সিদ্ধান্ত রিপোর্ট",
    report_desc: "আপনার স্টার্টআপের জন্য প্রমাণ-ভিত্তিক বিশ্লেষণ",
    why_fits: "কেন এটি উপযুক্ত",
    considerations: "বিবেচনা",
    recommended_investors: "প্রস্তাবিত বিনিয়োগকারী",
    sources_used: "এই বিশ্লেষণের জন্য ব্যবহৃত উত্স",
    run_new: "নতুন বিশ্লেষণ চালান",
    view_evidence: "সব প্রমাণ দেখুন",
    missing_info: "তথ্য নেই",
    no_risks_found: "প্রদত্ত তথ্যের ভিত্তিতে কোনো উল্লেখযোগ্য ঝুঁকি বা অসঙ্গতি চিহ্নিত করা হয়নি।",
    analysis_completed: "বিশ্লেষণ সম্পন্ন",
    match: "মিল",
    key_reasons: "মূল কারণ",
    analyzing_fit: "ফিট ফ্যাক্টর বিশ্লেষণ করা হচ্ছে...",
    how_it_works: "এটি কিভাবে কাজ করে",
    how_it_works_desc: "আমাদের AI আপনার স্টার্টআপ সেক্টর, পর্যায় এবং ভৌগোলিক অবস্থানের ভিত্তিতে হাজার হাজার বিনিয়োগকারী এবং বাজার ডেটা পয়েন্ট বিশ্লেষণ করে আপনাকে সবচেয়ে সঠিক সুপারিশ প্রদান করে।",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    analyze: "பகுப்பாய்வு",
    evidence: "ஆதாரம்",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    welcome: "நல்வரவு",
    recent_analysis: "சமீபத்திய பகுப்பாய்வு",
    new_analysis: "புதிய பகுப்பாய்வு",
    funding_fit: "நிதி பொருத்தம்",
    startup_description: "தொடக்க விளக்கம்",
    sector: "துறை",
    funding_stage: "நிதி நிலை",
    geography: "புவியியல்",
    language_settings: "மொழி அமைப்புகள்",
    interface_lang: "இடைமுக மொழி",
    interface_lang_desc: "இந்த மொழி FundingSense இடைமுகம் முழுவதும் பயன்படுத்தப்படும்",
    report_lang: "அறிக்கை மொழி",
    report_lang_desc: "நிதி பகுப்பாய்வு அறிக்கைகள் முன்னிருப்பாக இந்த மொழியில் உருவாக்கப்படும்.",
    save_prefs: "விருப்பங்களைச் சேமி",
    about_multilingual: "பல்லூடக ஆதரவு பற்றி",
    about_multilingual_desc: "FundingSense 8 முக்கிய இந்திய மொழிகளை ஆதரிக்கிறது, இது நிறுவனர்கள் மற்றும் முதலீட்டாளர்களுக்கு அவர்கள் விரும்பும் மொழியில் நிதி நுண்ணறிவை அணுக உதவுகிறது.",
    view_all: "அனைத்தையும் காண்க",
    no_analyses: "பகுப்பாய்வு எதுவும் இல்லை. உங்கள் முதல் பகுப்பாய்வை இங்கே காணத் தொடங்குங்கள்!",
    loading_analyses: "சமீபத்திய பகுப்பாய்வு ஏற்றப்படுகிறது...",
    loading_evidence: "ஆதாரம் ஏற்றப்படுகிறது...",
    just_now: "இப்போது",
    fit_score: "பொருத்த மதிப்பெண்",
    confidence: "நம்பிக்கை",
    analyses_run: "நடத்தப்பட்ட பகுப்பாய்வுகள்",
    investors_matched: "பொருந்திய முதலீட்டாளர்கள்",
    evidence_points: "ஆதார புள்ளிகள்",
    avg_fit_score: "சராசரி பொருத்த மதிப்பெண்",
    toggle_theme: "தீம் மாற்று",
    search_sources: "ஆதாரங்களைத் தேடு...",
    all_types: "அனைத்து வகைகள்",
    news: "செய்திகள்",
    policy: "கொள்கை",
    dataset: "தரவுத்தொகுப்பு",
    used_for: "பயன்படுத்தப்பட்டது",
    report_title: "நிதி முடிவு அறிக்கை",
    report_desc: "உங்கள் தொடக்கத்திற்கான சான்றுகள் அடிப்படையிலான பகுப்பாய்வு",
    why_fits: "இது ஏன் பொருந்துகிறது",
    considerations: "கருத்தில் கொள்ள வேண்டியவை",
    recommended_investors: "பரிந்துரைக்கப்பட்ட முதலீட்டாளர்கள்",
    sources_used: "இந்த பகுப்பாய்விற்காக பயன்படுத்தப்பட்ட ஆதாரங்கள்",
    run_new: "புதிய பகுப்பாய்வை நடத்து",
    view_evidence: "அனைத்து ஆதாரங்களையும் காண்க",
    missing_info: "தகவல் இல்லை",
    no_risks_found: "வழங்கப்பட்ட தரவுகளின் அடிப்படையில் குறிப்பிடத்தக்க அபாயங்கள் அல்லது முரண்பாடுகள் எதுவும் கண்டறியப்படவில்லை.",
  },
  te: {
    dashboard: "డ్యాష్‌బోర్డ్",
    analyze: "విశ్లేషణ",
    evidence: "సాక్ష్యం",
    settings: "సెట్టింగులు",
    logout: "లాగ్ అవుట్",
    welcome: "స్వాగతం",
    recent_analysis: "ఇటీవలి విశ్లేషణ",
    new_analysis: "కొత్త విશ્లేషణ",
    funding_fit: "ఫండింగ్ ఫిట్",
    startup_description: "స్టార్టప్ వివరణ",
    sector: "రంగం",
    funding_stage: "ఫండింగ్ దశ",
    geography: "భౌగోళిక ప్రాంతం",
    language_settings: "భాష సెట్టింగులు",
    interface_lang: "ఇంటర్‌ఫేస్ భాష",
    report_lang: "నివేదిక భాష",
    save_prefs: "ప్రాధాన్యతలను సేవ్ చేయి",
    no_risks_found: "అందించిన డేటా ఆధారంగా ఎటువంటి ముఖ్యమైన రిస్క్‌లు లేదా అసమానతలు గుర్తించబడలేదు.",
    analysis_completed: "విశ్లేషణ పూర్తಯింది",
    match: "మ్యాచ్",
    key_reasons: "ముఖ్య కారణాలు",
    analyzing_fit: "ఫిట్ కారకాలను విશ્ಲೆషిస్తోంది...",
    how_it_works: "ఇది ఎలా పనిచేస్తుంది",
    how_it_works_desc: "మా AI మీ స్టార్టప్ రంగం, దశ మరియు భౌగోళిక ప్రాంతం ఆధారంగా వేలాది పెట్టుబడిదారులు మరియు మార్కెట్ డేటా పాయింట్లను విశ్లేషించి మీకు అత్యంత ఖచ్చితమైన సిఫార్సులను అందిస్తుంది.",
    analyzing: "విశ్లేషిస్తోంది...",
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    analyze: "विश्लेषण",
    evidence: "पुरावा",
    settings: "सेटिंग्ज",
    logout: "लॉगआउट",
    welcome: "स्वागत आहे",
    recent_analysis: "अलीकडील विश्लेषण",
    new_analysis: "नवीन विश्लेषण",
    funding_fit: "फंडिंग फिट",
    startup_description: "स्टार्टअप वर्णन",
    sector: "क्षेत्र",
    funding_stage: "फंडिंग टप्पा",
    geography: "भूगोल",
    language_settings: "भाषा सेटिंग्ज",
    interface_lang: "इंटरफेस भाषा",
    interface_lang_desc: "ही भाषा संपूर्ण FundingSense इंटरफेसमध्ये वापरली जाईल",
    report_lang: "अहवाल भाषा",
    report_lang_desc: "फंडिंग विश्लेषण अहवाल डीफॉल्टनुसार या भाषेत तयार केले जातील.",
    save_prefs: "पसंती जतन करा",
    about_multilingual: "बहुभाषिक समर्थनाबद्दल",
    about_multilingual_desc: "FundingSense 8 मुख्य भारतीय भाषांना समर्थन देते, जे संस्थापक आणि गुंतवणूकदारांना त्यांच्या पसंतीच्या भाषेत फंडिंग इंटेलिजन्स मिळवण्यास सक्षम करते.",
    view_all: "सर्व पहा",
    no_analyses: "कोणतेही विश्लेषण आढळले नाही. तुमचे पहिले विश्लेषण पाहण्यासाठी इथे क्लिक करा!",
    loading_analyses: "अलीकडील विश्लेषण लोड होत आहे...",
    loading_evidence: "पुरावा लोड होत आहे...",
    just_now: "आत्ताच",
    fit_score: "फिट स्कोर",
    confidence: "विश्वास",
    analyses_run: "केलेली विश्लेषणे",
    investors_matched: "मिळलेले गुंतवणूकदार",
    evidence_points: "पुरावा गुण",
    avg_fit_score: "सरासरी फिट स्कोर",
    toggle_theme: "थीम बदला",
    search_sources: "स्त्रोत शोधा...",
    all_types: "सर्व प्रकार",
    news: "बातम्या",
    policy: "धोरण",
    dataset: "डेटासेट",
    used_for: "वापरले",
    report_title: "फंडिंग निर्णय अहवाल",
    report_desc: "तुमच्या स्टार्टअपसाठी पुरावा-आधारित विश्लेषण",
    why_fits: "हे का फिट बसते",
    considerations: "विचार करण्यासारख्या गोष्टी",
    recommended_investors: "शिफारस केलेले गुंतवणूकदार",
    sources_used: "या विश्लेषणासाठी वापरलेले स्त्रोत",
    run_new: "नवीन विश्लेषण करा",
    view_evidence: "सर्व पुरावे पहा",
    missing_info: "माहिती गहाळ",
    no_risks_found: "दिलेल्या डेटाच्या आधारावर कोणतेही लक्षणीय धोके किंवा विसंगती आढळली नाहीत.",
  },
  gu: {
    dashboard: "ડેશબોર્ડ",
    analyze: "વિશ્લેષણ",
    evidence: "પુરાવો",
    settings: "સેટિંગ્સ",
    logout: "લોગઆઉટ",
    welcome: "સ્વાગત છે",
    recent_analysis: "તાજેતરનું વિશ્લેષણ",
    new_analysis: "નવું વિશ્લેષણ",
    funding_fit: "ફંડિંગ ફિટ",
    startup_description: "સ્ટાર્ટઅપ વર્ણન",
    sector: "ક્ષેત્ર",
    funding_stage: "ફંડિંગ તબક્કો",
    geography: "ભૂગોળ",
    language_settings: "ભાષા સેટિંગ્સ",
    interface_lang: "ઇન્ટરફેસ ભાષા",
    interface_lang_desc: "આ ભાષા સમગ્ર FundingSense ઈન્ટરફેસમાં વપરાશે",
    report_lang: "રિપોર્ટ ભાષા",
    report_lang_desc: "ફંડિંગ વિશ્લેષણ અહેવાલો મૂળભૂત રીતે આ ભાષામાં જનરેટ કરવામાં આવશે.",
    save_prefs: "પસંદગીઓ સાચવો",
    about_multilingual: "બહુભાષી સપોર્ટ વિશે",
    about_multilingual_desc: "FundingSense 8 મુખ્ય ભારતીય ભાષાઓને સપોર્ટ કરે છે, જે સ્થાપકો અને રોકાણકારોને તેમની પસંદગીની ભાષામાં ફંડિંગ ઇન્ટેલિજન્સ એક્સેસ કરવા સક્ષમ બનાવે છે.",
    view_all: "બધું જુઓ",
    no_analyses: "કોઈ વિશ્લેષણ મળ્યું નથી. તમારું પ્રથમ વિશ્લેષણ અહીં જોવા માટે એક શરૂ કરો!",
    loading_analyses: "તાજેતરનું વિશ્લેષણ લોડ થઈ રહ્યું છે...",
    loading_evidence: "પુરાવો લોડ થઈ રહ્યો છે...",
    just_now: "હમણાં જ",
    fit_score: "ફિટ સ્કોર",
    confidence: "આત્મવિશ્વાસ",
    analyses_run: "ચલાવવામાં આવેલ વિશ્લેષણ",
    investors_matched: "મળેલા રોકાણકારો",
    evidence_points: "પુરાવા પોઈન્ટ",
    avg_fit_score: "સરેરાશ ફિટ સ્કોર",
    toggle_theme: "થીમ બદલો",
    search_sources: "સ્ત્રોતો શોધો...",
    all_types: "બધા પ્રકારો",
    news: "સમાચાર",
    policy: "નીતિ",
    dataset: "ડેટાસેટ",
    used_for: "વપરાયેલ",
    report_title: "ફંડિંગ નિર્ણય રિપોર્ટ",
    report_desc: "તમારા સ્ટાર્ટઅપ માટે પુરાવા-આધારિત વિશ્લેષણ",
    why_fits: "આ કેમ યોગ્ય છે",
    considerations: "ધ્યાનમાં લેવાની બાબતો",
    recommended_investors: "ભલામણ કરેલ રોકાણકારો",
    sources_used: "આ વિશ્લેષણ માટે વપરાયેલા સ્ત્રોતો",
    run_new: "નવું વિશ્લેષણ ચલાવો",
    view_evidence: "તમામ પુરાવા જુઓ",
    missing_info: "માહિતી નથી",
    no_risks_found: "આપેલ ડેટાના આધારે કોઈ નોંધપાત્ર જોખમો અથવા વિસંગતતાઓ ઓળખાઈ નથી.",
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    analyze: "ವಿಶ್ಲೇಷಣೆ",
    evidence: "ಪುರಾವೆ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    logout: "ಲಾಗ್ ಔಟ್",
    welcome: "ಸ್ವಾಗತ",
    recent_analysis: "ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆ",
    new_analysis: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ",
    funding_fit: "ಫಂಡಿಂಗ್ ಫಿಟ್",
    startup_description: "ಸ್ಟಾರ್ಟ್ಅಪ್ ವಿವರಣೆ",
    sector: "ವಲಯ",
    funding_stage: "ಫಂಡಿಂಗ್ ಹಂತ",
    geography: "ಭೂಗೋಳ",
    language_settings: "ಭಾಷಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    interface_lang: "ಇಂಟರ್ಫೇಸ್ ಭಾಷೆ",
    interface_lang_desc: "ಈ ಭಾಷೆಯನ್ನು FundingSense ಇಂಟರ್ಫೇಸ್ ಉದ್ದಕ್ಕೂ ಬಳಸಲಾಗುತ್ತದೆ",
    report_lang: "ವರದಿ ಭಾಷೆ",
    report_lang_desc: "ಫಂಡಿಂಗ್ ವಿಶ್ಲೇಷಣೆ ವರದಿಗಳನ್ನು ಪೂರ್ವನಿಯೋಜಿತವಾಗಿ ಈ ಭಾಷೆಯಲ್ಲಿ ರಚಿಸಲಾಗುತ್ತದೆ.",
    save_prefs: "ಪ್ರಾಶಸ್ತ್ಯಗಳನ್ನು ಉಳಿಸಿ",
    about_multilingual: "ಬಹುಭಾಷಾ ಬೆಂಬಲದ ಬಗ್ಗೆ",
    about_multilingual_desc: "FundingSense 8 ಪ್ರಮುಖ ಭಾರತೀಯ ಭಾಷೆಗಳನ್ನು ಬೆಂಬಲಿಸುತ್ತದೆ, ಇದು ಸಂಸ್ಥಾಪಕರು ಮತ್ತು ಹೂಡಿಕೆದಾರರಿಗೆ ತಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯಲ್ಲಿ ಫಂಡಿಂಗ್ ಇಂಟೆಲಿಜೆನ್ಸ್ ಅನ್ನು ಪ್ರವೇಶಿಸಲು ಅನುವು ಮಾಡಿಕೊಡುತ್ತದೆ.",
    view_all: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    no_analyses: "ಯಾವುದೇ ವಿಶ್ಲೇಷಣೆ ಕಂಡುಬಂದಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಇಲ್ಲಿ ನೋಡಲು ಒಂದನ್ನು ಪ್ರಾರಂಭಿಸಿ!",
    loading_analyses: "ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    loading_evidence: "ಪುರಾವೆ ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    just_now: "ಈಗ ತಾನೇ",
    fit_score: "ಫಿಟ್ ಸ್ಕೋರ್",
    confidence: "ನಂಬಿಕೆ",
    analyses_run: "ನಡೆಸಿದ ವಿಶ್ಲೇಷಣೆಗಳು",
    investors_matched: "ಹೊಂದಾಣಿಕೆಯಾದ ಹೂಡಿಕೆದಾರರು",
    evidence_points: "ಪುರಾವೆ ಅಂಕಗಳು",
    avg_fit_score: "ಸರಾಸರಿ ಫಿಟ್ ಸ್ಕೋರ್",
    toggle_theme: "ಥೀಮ್ ಬದಲಿಸಿ",
    search_sources: "ಮೂಲಗಳನ್ನು ಹುಡುಕಿ...",
    all_types: "ಎಲ್ಲಾ ವಿಧಗಳು",
    news: "ಸುದ್ದಿ",
    policy: "ನೀತಿ",
    dataset: "ಡೇಟಾಸೆಟ್",
    used_for: "ಬಳಸಲಾಗಿದೆ",
    report_title: "ಫಂಡಿಂಗ್ ನಿರ್ಧಾರ ವರದಿ",
    report_desc: "ನಿಮ್ಮ ಆರಂಭಿಕ ಹಂತದ ಉದ್ಯಮಕ್ಕಾಗಿ ಸಾಕ್ಷ್ಯ-ಆಧಾರಿತ ವಿಶ್ಲೇಷಣೆ",
    why_fits: "ಇದು ಏಕೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ",
    considerations: "ಪರಿಗಣನೆಗಳು",
    recommended_investors: "ಶಿಫಾರಸು ಮಾಡಿದ ಹೂಡಿಕೆದಾರರು",
    sources_used: "ಈ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಬಳಸಲಾದ ಮೂಲಗಳು",
    run_new: "ಹೊಸ ವಿಶ್ಲೇಷಣೆಯನ್ನು ನಡೆಸಿ",
    view_evidence: "ಎಲ್ಲಾ ಪುರಾವೆಗಳನ್ನು ನೋಡಿ",
    missing_info: "ಮಾಹಿತಿ ಇಲ್ಲ",
    no_risks_found: "ಒದಗಿಸಿದ ಡೇಟಾವನ್ನು ಆಧರಿಸಿ ಯಾವುದೇ ಗಮನಾರ್ಹ ಅಪಾಯಗಳು ಅಥವಾ ಅಸಂಗತತೆಗಳನ್ನು ಗುರುತಿಸಲಾಗಿಲ್ಲ.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("uiLanguage");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("uiLanguage", lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
